### ISSUE TITLE
Crash on Execution

### ISSUE THREAD

**Issue by brodyhoskins** [ioquatix/cloudflare-dns-update#4]
Hello,

I am getting the following error on every startup, on both Ruby 2.3.0/2.4.0, Ubuntu 17.04/macOS Sierra using both `rbenv` and `rvm` (in this case Ubuntu 17.04 Ruby 2.3.0 with `rbenv`):

```
Executing content command: curl -s http://ipv6.icanhazip.com/s
Elapsed Time: 0.407s
cloudflare-dns-update-2.0.1/lib/cloudflare/dns/update/command.rb:112:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cloudflare-dns-update-2.0.1/lib/cloudflare/dns/update/command.rb:112:in `block in update_domains'
	from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pstore.rb:331:in `block in transaction'
	from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pstore.rb:330:in `catch'
	from ~/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pstore.rb:330:in `transaction'
	from ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cloudflare-dns-update-2.0.1/lib/cloudflare/dns/update/command.rb:104:in `update_domains'
	from ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cloudflare-dns-update-2.0.1/lib/cloudflare/dns/update/command.rb:162:in `block in invoke'
	from ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/samovar-1.6.0/lib/samovar/command/track_time.rb:28:in `track_time'
	from ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cloudflare-dns-update-2.0.1/lib/cloudflare/dns/update/command.rb:155:in `invoke'
	from ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cloudflare-dns-update-2.0.1/bin/cloudflare-dns-update:25:in `<top (required)>'
	from ~/.rbenv/versions/2.3.0/bin/cloudflare-dns-update:23:in `load'
	from ~/.rbenv/versions/2.3.0/bin/cloudflare-dns-update:23:in `<main>'
```

(I shortened my home folder to ~ for some sanity.)

What is causing this issue? Thanks.

**Comment by ioquatix** [comment]
It looks like you are missing the zone in the configuration file?

https://github.com/ioquatix/cloudflare-dns-update/blob/b71ad17c7c83f316942831e42eba1b4d843aa993/lib/cloudflare/dns/update/command.rb#L112-L114

Can you show me your config file (please redact your API key).

**Comment by brodyhoskins** [comment]
Config:

```
---
:key: [redacted]
:email: brody.h@icloud.com
:zone: brody.ninja
:domains:
- &1
  rec_id: '710598619'
  rec_hash: 330deccb69eb121b9c26e25b947aa59a
  zone_name: [redacted: example.com]
  name: [redacted: sub.sub.example.com]
  display_name: [redacted: sub.sub]
  type: AAAA
  prio: 
  content: [redacted: IPv6 address]
  display_content: [redacted: IPv6 address]
  ttl: '1'
  ttl_ceil: 86400
  ssl_id: '5720508'
  ssl_status: V
  ssl_expires_on: 
  auto_ttl: 1
  service_mode: '0'
  props:
    proxiable: 0
    cloud_on: 0
    cf_open: 1
    vanity_lock: 0
    ssl: 1
    expired_ssl: 0
    expiring_ssl: 0
    pending_ssl: 0
:content_command: curl -s http://ipv6.icanhazip.com/s
:domain: *1
```

Though this config is for IPv6, it happens with IPv4 as well.
